# -*- coding: utf-8 -*-
"""preceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFaMpqR9ERMCx1lMW9B2ihJXbZGOsYo2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
d='https://archive.ics.uci.edu/dataset/53/iris'
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',header=None)

df

y=df.iloc[0:100,4].values
y=np.where(y=='Iris-setosa',0,1)
X=df.iloc[0:100,[0,2]].values

class preceptron:
  def __init__(self,eta=0.01,n_iter=50,random_state=1):
    self.eta=eta
    self.n_iter=n_iter
    self.random_state=random_state

  def fit(self,X,y):
    regn=np.random.RandomState(self.random_state)
    self.w_=regn.normal(loc=0.0,scale=0.01,size=1+X.shape[1])
    self.errors_=[]

    for _ in range(self.n_iter):
      errors=0
      for xi,target in zip(X,y):
        updat=self.eta*(target-self.predict(xi))
        self.w_[1:]+=updat*xi
        self.w_[0]+=updat
        errors+=int(updat!=0.0)
      self.errors_.append(errors)
    return self

  def net_input(self,X):
    return np.dot(X,self.w_[1:])+self.w_[0]

  def predict(self,X):
    return np.where(self.net_input(X)>=0.0,1,0)

ppn=preceptron(eta=0.1,n_iter=10)
ppn.fit(X,y)

plt.plot(range(1,len(ppn.errors_)+1),ppn.errors_,marker='o')
plt.xlabel('Epochs')
plt.ylabel('Number of misclassifications')
plt.show()

final_weight=ppn.w_[1:]
 final_bias=ppn.w_[0]
 print(final_weight)
 print(final_bias)

from matplotlib.colors import ListedColormap

def plot_decision_regions(X, y, classifier, resolution=0.02):
    # setup marker generator and color map
    markers = ('o', 's', '^', 'v', '<')
    colors = ('red', 'blue', 'lightgreen', 'gray', 'cyan')
    cmap = ListedColormap(colors[:len(np.unique(y))])

    # plot the decision surface
    x1_min, x1_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    x2_min, x2_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx1, xx2 = np.meshgrid(np.arange(x1_min, x1_max, resolution),
                           np.arange(x2_min, x2_max, resolution))
    lab = classifier.predict(np.array([xx1.ravel(), xx2.ravel()]).T)
    lab = lab.reshape(xx1.shape)
    plt.contourf(xx1, xx2, lab, alpha=0.3, cmap=cmap)
    plt.xlim(xx1.min(), xx1.max())
    plt.ylim(xx2.min(), xx2.max())

    # plot class examples
    for idx, cl in enumerate(np.unique(y)):
        plt.scatter(x=X[y == cl, 0],
                    y=X[y == cl, 1],
                    alpha=0.8,
                    c=colors[idx],
                    marker=markers[idx],
                    label=f'class {cl}',
                    edgecolor='black')

plot_decision_regions(X, y, classifier=ppn)
plt.xlabel('Sepal length [cm]')
plt.ylabel('Petal length [cm]')
plt.legend(loc='upper left')
plt.show()

